name: "Telegram Notification Push"

on:
  push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.ID }}
          token: ${{ secrets.TOKEN }}
          message: |
            ${{ github.actor }} created commit: 
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}

            https://github.com/${{ github.repository }}/commit/${{ github.sha }}
